 2018-05-07 20:53:04,366 [P4736/D3/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.10.4 application starting on LAPTOP-H8OG52DV
 2018-05-07 20:53:04,428 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2018-05-07 20:53:04,444 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 12ms)
 2018-05-07 20:53:04,564 [P4736/D3/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-05-07 20:53:04,568 [P4736/D3/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-05-07 20:53:04,571 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:53:04,970 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 398ms)
 2018-05-07 20:53:04,971 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2018-05-07 20:53:04,984 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 13ms)
 2018-05-07 20:53:05,026 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:53:05,027 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2018-05-07 20:53:05,027 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2018-05-07 20:53:05,037 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 9ms)
 2018-05-07 20:53:05,037 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:53:05,038 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:53:05,038 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2018-05-07 20:53:05,050 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 11ms)
 2018-05-07 20:53:05,085 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:53:05,086 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:53:05,086 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2018-05-07 20:53:05,098 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 12ms)
 2018-05-07 20:53:05,099 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:53:05,099 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:53:05,099 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2018-05-07 20:53:05,116 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 16ms)
 2018-05-07 20:53:10,265 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:10,265 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:10,468 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2018-05-07 20:53:10,484 [P4736/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 10ms)
 2018-05-07 20:53:10,648 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:10,648 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:11,670 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:11,670 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:12,691 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:12,691 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:13,722 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:13,722 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:14,753 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:14,753 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:15,784 [P4736/D3/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:53:15,784 [P4736/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:53:15,799 [P4736/D3/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   at Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
 2018-05-07 20:53:25,966 [P4736/D3/T32] INFO  Umbraco.Core.MainDom - Stopping...
 2018-05-07 20:53:25,966 [P4736/D3/T32] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2018-05-07 20:53:26,294 [P4736/D3/T32] INFO  Umbraco.Web.ExamineStartup - Complete (took 337ms)
 2018-05-07 20:53:26,310 [P4736/D3/T32] INFO  Umbraco.Core.MainDom - Released MainDom.
 2018-05-07 20:53:56,428 [P4736/D3/T32] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
 2018-05-07 20:59:08,541 [P4736/D4/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.10.4 application starting on LAPTOP-H8OG52DV
 2018-05-07 20:59:08,572 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2018-05-07 20:59:08,584 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 11ms)
 2018-05-07 20:59:08,666 [P4736/D4/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-05-07 20:59:08,669 [P4736/D4/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-05-07 20:59:08,672 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:59:08,732 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 60ms)
 2018-05-07 20:59:08,732 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2018-05-07 20:59:08,733 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 1ms)
 2018-05-07 20:59:08,761 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:59:08,762 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:59:08,762 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2018-05-07 20:59:08,762 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2018-05-07 20:59:08,762 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:59:08,762 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:59:08,763 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2018-05-07 20:59:08,764 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 1ms)
 2018-05-07 20:59:08,780 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:59:08,780 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:59:08,780 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2018-05-07 20:59:08,780 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2018-05-07 20:59:08,780 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 20:59:08,781 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 20:59:08,781 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2018-05-07 20:59:08,781 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 0ms)
 2018-05-07 20:59:10,922 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:10,928 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:10,998 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2018-05-07 20:59:11,001 [P4736/D4/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 2ms)
 2018-05-07 20:59:11,090 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:11,090 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:12,109 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:12,110 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:13,131 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:13,132 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:14,148 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:14,148 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:15,167 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:15,168 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:16,185 [P4736/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Dev\GitHub\BasicFrontend\BasicFrontend.Umbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-05-07 20:59:16,185 [P4736/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-05-07 20:59:16,189 [P4736/D4/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   at Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
 2018-05-07 20:59:26,321 [P4736/D4/T38] INFO  Umbraco.Core.MainDom - Stopping...
 2018-05-07 20:59:26,322 [P4736/D4/T38] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2018-05-07 20:59:26,324 [P4736/D4/T38] INFO  Umbraco.Web.ExamineStartup - Complete (took 2ms)
 2018-05-07 20:59:26,324 [P4736/D4/T38] INFO  Umbraco.Core.MainDom - Released MainDom.
 2018-05-07 20:59:56,348 [P4736/D4/T38] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
 2018-05-07 21:07:49,076 [P4736/D5/T49] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.10.4 application starting on LAPTOP-H8OG52DV
 2018-05-07 21:07:49,098 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2018-05-07 21:07:49,117 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Hash determined (took 19ms)
 2018-05-07 21:07:49,177 [P4736/D5/T49] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-05-07 21:07:49,177 [P4736/D5/T49] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-05-07 21:07:49,183 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:07:49,244 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 60ms)
 2018-05-07 21:07:49,244 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2018-05-07 21:07:49,246 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 1ms)
 2018-05-07 21:07:49,286 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:07:49,288 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2018-05-07 21:07:49,289 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2018-05-07 21:07:49,289 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2018-05-07 21:07:49,290 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:07:49,290 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:07:49,290 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2018-05-07 21:07:49,292 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 2ms)
 2018-05-07 21:07:49,305 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:07:49,306 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:07:49,306 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2018-05-07 21:07:49,307 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2018-05-07 21:07:49,307 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:07:49,307 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:07:49,307 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2018-05-07 21:07:49,308 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 0ms)
 2018-05-07 21:07:52,654 [P4736/D5/T49] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2018-05-07 21:07:53,261 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2018-05-07 21:07:53,264 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 2ms)
 2018-05-07 21:07:53,352 [P4736/D5/T49] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2018-05-07 21:07:53,523 [P4736/D5/T49] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2018-05-07 21:07:53,525 [P4736/D5/T49] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2018-05-07 21:07:53,698 [P4736/D5/T49] WARN  Umbraco.Core.Sync.DatabaseServerMessenger - No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.
 2018-05-07 21:07:53,759 [P4736/D5/T49] INFO  umbraco.content - Load Xml from file...
 2018-05-07 21:07:54,045 [P4736/D5/T49] INFO  umbraco.content - Loaded Xml from file.
 2018-05-07 21:07:54,064 [P4736/D5/T49] INFO  umbraco.content - Loading content from database...
 2018-05-07 21:07:55,974 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalMemberIndexer, NodeId=-1
 2018-05-07 21:07:56,275 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - member, Provider=InternalMemberIndexer, NodeId=-1
 2018-05-07 21:07:56,487 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - member, took 211ms, Provider=InternalMemberIndexer, NodeId=-1
 2018-05-07 21:07:56,490 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalIndexer, NodeId=-1
 2018-05-07 21:07:56,526 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=InternalIndexer, NodeId=-1
 2018-05-07 21:07:56,801 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:07:56,802 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:07:56,803 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2018-05-07 21:07:56,821 [P4736/D5/T49] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 17ms)
 2018-05-07 21:07:57,205 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 677ms, Provider=InternalIndexer, NodeId=-1
 2018-05-07 21:07:57,205 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=InternalIndexer, NodeId=-1
 2018-05-07 21:07:57,526 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 321ms, Provider=InternalIndexer, NodeId=-1
 2018-05-07 21:07:57,527 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=ExternalIndexer, NodeId=-1
 2018-05-07 21:07:57,576 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=ExternalIndexer, NodeId=-1
 2018-05-07 21:07:57,711 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 135ms, Provider=ExternalIndexer, NodeId=-1
 2018-05-07 21:07:57,711 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=ExternalIndexer, NodeId=-1
 2018-05-07 21:07:57,765 [P4736/D5/T49] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 52ms, Provider=ExternalIndexer, NodeId=-1
 2018-05-07 21:07:57,830 [P4736/D5/T49] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 8856ms)
 2018-05-07 21:07:59,248 [P4736/D5/T45] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://frontend.local:80/umbraco
 2018-05-07 21:07:59,252 [P4736/D5/T45] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://frontend.local:80/umbraco (UmbracoModule request)
 2018-05-07 21:07:59,252 [P4736/D5/T39] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://frontend.local:80/umbraco (UmbracoModule request)
 2018-05-07 21:08:00,020 [P4736/D5/T48] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:08:00,080 [P4736/D5/T48] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:08:04,751 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:04,751 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:04,752 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2018-05-07 21:08:04,766 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 14ms)
 2018-05-07 21:08:05,291 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:05,291 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:05,291 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2018-05-07 21:08:05,298 [P4736/D5/T39] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 7ms)
 2018-05-07 21:08:23,416 [P4736/D5/T38] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username mailto.kaysta@gmail.com from IP address 127.0.0.1
 2018-05-07 21:08:23,419 [P4736/D5/T38] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: mailto.kaysta@gmail.com logged in from IP address 127.0.0.1
 2018-05-07 21:08:27,651 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:27,651 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:27,651 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2018-05-07 21:08:27,664 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 12ms)
 2018-05-07 21:08:27,692 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:27,692 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:27,692 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2018-05-07 21:08:27,693 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2018-05-07 21:08:27,697 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:27,698 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:27,698 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2018-05-07 21:08:27,711 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 12ms)
 2018-05-07 21:08:27,748 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:27,748 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:27,748 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2018-05-07 21:08:27,770 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 21ms)
 2018-05-07 21:08:28,233 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:08:28,234 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:08:28,234 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2018-05-07 21:08:28,243 [P4736/D5/T47] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 9ms)
 2018-05-07 21:09:00,009 [P4736/D5/T50] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2018-05-06 21:08:59
 2018-05-07 21:09:19,845 [P4736/D5/T34] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:09:20,352 [P4736/D5/T34] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-05-07 21:09:20,352 [P4736/D5/T34] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-05-07 21:09:20,353 [P4736/D5/T34] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2018-05-07 21:09:20,371 [P4736/D5/T34] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 18ms)
 2018-05-07 21:09:24,663 [P4736/D5/T46] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:09:24,680 [P4736/D5/T46] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:09:49,970 [P4736/D5/T30] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:09:55,114 [P4736/D5/T34] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:09:55,130 [P4736/D5/T34] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:23:06,324 [P4736/D5/T47] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Site Global' with Id '1090' has been published.
 2018-05-07 21:23:10,839 [P4736/D5/T6] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:23:10,839 [P4736/D5/T6] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:28:28,722 [P4736/D5/T58] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:28:33,191 [P4736/D5/T61] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:28:33,191 [P4736/D5/T61] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:28:41,173 [P4736/D5/T60] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:28:45,469 [P4736/D5/T71] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:28:45,469 [P4736/D5/T71] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:33:20,689 [P4736/D5/T70] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:33:24,860 [P4736/D5/T70] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:33:24,906 [P4736/D5/T70] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:35:18,951 [P4736/D5/T88] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:35:23,403 [P4736/D5/T61] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:35:23,403 [P4736/D5/T61] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:38:36,242 [P4736/D5/T62] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:38:40,553 [P4736/D5/T78] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:38:40,553 [P4736/D5/T78] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 21:38:58,361 [P4736/D5/T71] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2018-05-07 21:45:42,731 [P4736/D5/T52] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Home' with Id '1089' has been published.
 2018-05-07 21:45:47,152 [P4736/D5/T48] INFO  umbraco.content - Save Xml to file...
 2018-05-07 21:45:47,152 [P4736/D5/T48] INFO  umbraco.content - Saved Xml to file.
 2018-05-07 22:05:07,493 [P4736/D5/T63] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: mailto.kaysta@gmail.com, IP Address: 127.0.0.1
 2018-05-07 22:07:34,802 [P4736/D5/T62] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2018-05-07 22:09:53,842 [P4736/D5/T62] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
